# logging.level.org.springframework.security=DEBUG
logging:
  file:
    name: /tmp/playlist/play-list.log


spring:
  datasource:
  #  url: jdbc:h2:mem:bookstore
    url: jdbc:mysql://localhost:3306/bookstore?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: bookstore
    password: bookstore
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/change-log.xml
  mail:
    host: smtp.gmail.com
    username: zdjavapol9@gmail.com
    password: Zdjavapol9!@
    port: 587
    test-connection: true
#    properties:
#      mail.transport.protocol: smtp
#      mail.smtp.port: 587
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true
