# logging.level.org.springframework.security=DEBUG
logging:
  file:
    name: /tmp/playlist/play-list.log


spring:
  datasource:
    url: jdbc:h2:mem:playlist
#    url: jdbc:mysql://192.168.238.130:3306/bookstore
#    username: boookstore
#    password: bookstore
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/change-log.xml
